version: "3.9"
networks:
  ollama_ollama-network:
    external: true

services:
  neo4j:
    image: neo4j:5.16.0
    volumes:
      - ./data/data:/data:rw
      - ./data/logs:/logs:rw
      - ./data/conf:/var/lib/neo4j/conf:rw
      - ./data/import:/var/lib/neo4j/import:rw
      - ./data/plugins:/plugins:rw
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_auth__minimum__password__length=6
      - NEO4J_server_memory_heap_max__size=513M
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
#      - NEO4J_AUTH=none
    networks:
      - ollama_ollama-network