version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next:0.2.1
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "8181:8181"
    environment:
      - PANDORA_NEXT_LICENSE="在这里获取：https://dash.pandoranext.com"
    volumes:
      - ./data:/data
