auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "kibana:5601"

# kibana 索引模式
setup.dashboards.index: "logstash-auditbeat*"

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
#  index: 'filebeat'