filebeat.config:
  inputs:
    enabled: true
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true
    reload.period: 10s
  modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "kibana:5601"

# kibana 索引模式
setup.dashboards.index: "logstash-filebeat*"

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  enabled: false
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
#  index: 'filebeat'

# ------------------------------- Console Output 仅用于调试，将产生大量日志，可能把磁盘空间用完 -------------------------------
output.console:
  enabled: false
  pretty: true
  codec.json:
    pretty: true
    escape_html: false

# -------------------------------- Redis Output --------------------------------
output.redis:
   enabled: false
   hosts: ["docker-redis:6379"]   #输出到redis的机器
#   password: "password"
   key: "nginx_logs"   #redis中日志数据的key值ֵ
   db: 0
   timeout: 5

# -------------------------------- Kafka Output --------------------------------
output.kafka:
  enabled: false
  hosts: ["kafka:9092"]
  topic: beats