version: '3'

networks:
  web-network:

services:
  docker-php-jupyter:
    image: registry.cn-hangzhou.aliyuncs.com/cuiw/php-jupyter:8.1.9-fpm-v1.1
    hostname: php-jupyter
    ports:
      - 8888:8888
    volumes:
      - ./data:/notebooks
      - ./config:/root/.jupyter
    restart: always
    tty: true
    networks:
      - web-network