version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.3.1-ce.0'
    hostname: git.cuiwei.net
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.cuiwei.net'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
