# Define a directory to load monitor definitions from. Definitions take the form
# of individual yaml files.
heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 5s


heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    - http://cuiwei.net

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "kibana:5601"

# kibana 索引模式
# setup.dashboards.index: "logstash-heartbeat*"

# output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
#  index: 'filebeat'