version: '3'

networks:
  web-network:

services:
  docker-alist:
    image: 'xhofe/alist:v3.15.1'
    volumes:
      - './data:/opt/alist/data'
    ports:
      - '5244:5244'
#    environment:
#      - PUID=0
#      - PGID=0
#      - UMASK=022
#      - TZ=UTC
    networks:
      - web-network