version: "3"
services:
  chrome:
#    selenium/standalone-firefox:4.1.4-20220427
#    selenium/standalone-edge:4.1.4-20220427
    image: selenium/standalone-chrome:4.1.4-20220427
    shm_size: 2gb
    container_name: standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
    environment:
      - VNC_VIEW_ONLY=1 #查看模式
      - VNC_NO_PASSWORD=1 #取消密码验证

#  chrome_video:
#    image: selenium/video:ffmpeg-4.3.1-20220427
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - chrome
#    environment:
#      - DISPLAY_CONTAINER_NAME=chrome
#      - FILE_NAME=chrome_video.mp4
